### ISSUE TITLE
[SUGGESTION] A config file

### ISSUE THREAD

**Issue by Sunconure11** [0SoggyMustache0/NaturalFauna#1]
So one can control, disable, or increase mob spawns, for instance. Preferably on an individual mob scale (i.e being able to turn up the spawn rates for one mob, but turning off spawns for another mob, for instance)

**Comment by Mnesikos** [comment]
Yes, absolutely! Already planning to add this when I next get the chance. Thank you!

**Comment by Mnesikos** [comment]
Forgot to close this earlier, haha! Config file included in the latest update. [https://minecraft.curseforge.com/projects/natural-fauna-mod-a-zawa-addon/files/2654313](https://minecraft.curseforge.com/projects/natural-fauna-mod-a-zawa-addon/files/2654313)
