### ISSUE TITLE
Crash when adding OTG biome to spawnlist

### ISSUE THREAD

**Issue by Ezoteric** [0SoggyMustache0/NaturalFauna#11]
As topic states

Crashlog:
[https://paste.dimdev.org/veyahipedo.mccrash](url)

**Comment by JoelZBub** [comment]
OTG doesn't use forge's biome dictionary. This isn't a bug in Natural Fauna.
Adding mobs to OTG biomes is done in OTG configs. Have fun!

Also, your crash log link is broken

**Comment by Ezoteric** [comment]
ait weird, thnx.
Anyway it seems this mod listens to the OTG rename to biome stuff so it does spawn as long as it renamed :) you can close it :)
