### ISSUE TITLE
Crash w/ ZAWA v1.5.4

### ISSUE THREAD

**Issue by WenXin20** [0SoggyMustache0/NaturalFauna#4]
Forge v14.23.5.2807-1.12.2
Natural Fauna v1.3.0
Bookworm v2.1.0
ZAWA v1.5.4

I got this crash after trying to load my world with ZAWA 1.5.4
[Crash Log](https://gist.github.com/WenXin20/3234052387057ab977c495b1852300c6)

**Comment by Daihok41** [comment]
Yup can confirm crashs with new Zawa 1.5.4 when adding in natural fauna

**Comment by JoelZBub** [comment]
Known issue. Report it to Natural Fauna

Edit: NVM

**Comment by Mnesikos** [comment]
Updated and solved with NF 1.3.1
