### ISSUE TITLE
Crash with Project Vibrant Journey mod

### ISSUE THREAD

**Issue by viceroy369** [0SoggyMustache0/NaturalFauna#6]
Unfortunately the crash report doesn't have much information but I've narrowed down this crash to be caused by some interaction between Natural Fauna and Project Vibrant Journeys mod:

https://paste.dimdev.org/abevawasay.mccrash

**Comment by JoelZBub** [comment]
Post your latest.log file as well. I doubt you're gonna get much help on this one. You've got so many core mods present.

**Comment by viceroy369** [comment]
I meant to post this crash - there's only 2 core mods present here:

https://paste.dimdev.org/elenofinuf.mccrash

It's the previous version of natural fauna but the crash is the same.

**Comment by Mnesikos** [comment]
I absolutely cannot help you with that first report. There are too many other mods, and absolutely no information. The second report uses Natural Fauna 1.3.0, and as I suggested to your comment on the curseforge page, you need to update it to 1.3.1 because otherwise it crashes for sure with ZAWA 1.5.4.

Since the crash is the same despite NF's version, I'm assuming you have removed NF to confirm it is the source of the crash? Does it crash with only NF 1.3.1, Bookworm 2.1.0, ZAWA 1.5.4, and Project Vibrant Journeys? The more information you provide, the quicker and easier I can resolve this conflict.

**Comment by viceroy369** [comment]
Yes, I have removed NF and confirmed it is indeed the source of the crash. Here's a recreation of it using the latest NF https://paste.dimdev.org/eviqapexig.mccrash

The reason I had those other biome mods in the crash report is that that is how I could recreate a specific seed where the crash happens right at spawn. The crash is unpredictable and sometimes happens thousands of blocks out (but always happens in the same place in the same seed) so it's pretty time consuming to test but I will try to test with just those 4 mods.

I suppose it might also be something to do with JAID or one of the other biome mods but I have a world with all those mods _except_ PVJ that I've explored for tens of thousands of blocks and never had this crash and started coming across it frequently in new worlds created with PVJ. Removing NF fixes it so I can only assume it's an interaction between those two.

**Comment by JoelZBub** [comment]
I'll ask again...
Post the latest.log file from the logs folder.

Also, if you have to install a specific combo of mods to get it to crash on one specific seed, you should probably be looking at that combo of mods. 
If you can't duplicate it with only the mods you are blaming for the crash, it's not those mods. ;)
If you want further help do this:
1. Post the latest.log from the crashed world referenced above.
2. Test with ONLY the mods the developer has requested, and upload any crash report and log if available.

If you want help on an issue, do what the developer asks you to do. (Or anyone else who offers help, for that matter.)

**Comment by gkazan** [comment]
Do what Joel told you and make a new issue.
