### ISSUE TITLE
Water creatures spawning?

### ISSUE THREAD

**Issue by jaz000** [0SoggyMustache0/NaturalFauna#7]
Hello!

I've never seen water creatures like nautilus, stingray, and paddlefish spawn naturally - are they working?

It looks to me like they are being registered to the biomes normal spawn list - when I've seen that done (at least with current mods) I've not seen it work for water creatures type. Zawa and mo creatures use their own spawning machanism for water creatures I think (if I override that and use something else like biome tweaker to spawn them it doesn't work).

Of course I do have a lot of other mods loaded so there could be some interaction but I read a lot about difficulty getting watercreatures to spawn.

I also think it would be good to have better biome control if possible (like the zawa config) - I think it's adding them to biomes by type? So while it's picked up a lot of other biomes in the pack (handy!) I'm putting together it's also added them to galacticraft dimensions :-) (they may not actually spawn there - I've not been there to check yet).

**Comment by JoelZBub** [comment]
Try using the mod called In Control to set spawns. It's been the most effective of all that I've tried.
Alternatively, Custom Mob Spawner that is used by Mo Creatures may work as well.

**Comment by Mnesikos** [comment]
Not gonna lie, completely overlooked that there even _are_ water creatures in this mod. :sweat_smile: I'll definitely get custom spawn biomes configuration added, and look into how this mod handles spawning them itself as well. Thanks so much for the heads up!

**Comment by CREEATION** [comment]
@Mnesikos Hey, any news on the custom spawn biomes config? 🐢

**Comment by Mnesikos** [comment]
It'll be in the next update! (Which will be for the next ZAWA update whenever that is released :wink:)

**Comment by Mnesikos** [comment]
Fixed with the latest release!
