### ISSUE TITLE
nothing cant be crafted via hides or furs

### ISSUE THREAD

**Issue by KenyMylankca** [0SoggyMustache0/NaturalFauna#8]
cheetah fur, gnu hide, hyena fur, gazelle hide,. nothing to do with them. consider adding recipies or some items like armor?

**Comment by JoelZBub** [comment]
Please note this clearly displayed announcement on the project's Curseforge download page:
![NFnotice](https://user-images.githubusercontent.com/12024500/57582303-ebb2ff80-7490-11e9-9f88-c91014d6c275.png)

This project is only being maintained for compatibility.
If you care to add your own recipes to your modpack, you might try using 
[CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker).

**Comment by gkazan** [comment]
Answered

**Comment by KenyMylankca** [comment]
nvm i already removed this mod and not playing anymore..it's ok. but it was fun..
